<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerI1exrtu\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerI1exrtu/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerI1exrtu.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerI1exrtu\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerI1exrtu\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'I1exrtu',
    'container.build_id' => 'd5e30261',
    'container.build_time' => 1569578784,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerI1exrtu');
